#pragma once

#define BUTTON_ACTION_RELEASE 0
#define BUTTON_ACTION_PRESS 1

enum ButtonCode
{
	BUTTON_MOUSE_LEFT = 0, // GLFW_MOUSE_BUTTON_LEFT
	BUTTON_MOUSE_MIDDLE = 2, // GLFW_MOUSE_BUTTON_MIDDLE
	BUTTON_MOUSE_RIGHT = 1, // GLFW_MOUSE_BUTTON_RIGHT

	BUTTON_KEY_A = 65, // GLFW_KEY_A
	BUTTON_KEY_B = 66, // GLFW_KEY_B
	BUTTON_KEY_C = 67, // GLFW_KEY_C
	BUTTON_KEY_D = 68, // GLFW_KEY_D
	BUTTON_KEY_E = 69, // GLFW_KEY_E
	BUTTON_KEY_F = 70, // GLFW_KEY_F
	BUTTON_KEY_G = 71, // GLFW_KEY_G
	BUTTON_KEY_H = 72, // GLFW_KEY_H
	BUTTON_KEY_I = 73, // GLFW_KEY_I
	BUTTON_KEY_J = 74, // GLFW_KEY_J
	BUTTON_KEY_K = 75, // GLFW_KEY_K
	BUTTON_KEY_L = 76, // GLFW_KEY_L
	BUTTON_KEY_M = 77, // GLFW_KEY_M
	BUTTON_KEY_N = 78, // GLFW_KEY_N
	BUTTON_KEY_O = 79, // GLFW_KEY_O
	BUTTON_KEY_P = 80, // GLFW_KEY_P
	BUTTON_KEY_Q = 81, // GLFW_KEY_Q
	BUTTON_KEY_R = 82, // GLFW_KEY_R
	BUTTON_KEY_S = 83, // GLFW_KEY_S
	BUTTON_KEY_T = 84, // GLFW_KEY_T
	BUTTON_KEY_U = 85, // GLFW_KEY_U
	BUTTON_KEY_V = 86, // GLFW_KEY_V
	BUTTON_KEY_W = 87, // GLFW_KEY_W
	BUTTON_KEY_X = 88, // GLFW_KEY_X
	BUTTON_KEY_Y = 89, // GLFW_KEY_Y
	BUTTON_KEY_Z = 90, // GLFW_KEY_Z

	BUTTON_KEY_0 = 48, // GLFW_KEY_0
	BUTTON_KEY_1 = 49, // GLFW_KEY_1
	BUTTON_KEY_2 = 50, // GLFW_KEY_2
	BUTTON_KEY_3 = 51, // GLFW_KEY_3
	BUTTON_KEY_4 = 52, // GLFW_KEY_4
	BUTTON_KEY_5 = 53, // GLFW_KEY_5
	BUTTON_KEY_6 = 54, // GLFW_KEY_6
	BUTTON_KEY_7 = 55, // GLFW_KEY_7
	BUTTON_KEY_8 = 56, // GLFW_KEY_8
	BUTTON_KEY_9 = 57, // GLFW_KEY_9

	BUTTON_KEY_F1 = 290, // GLFW_KEY_F1
	BUTTON_KEY_F2 = 291, // GLFW_KEY_F2
	BUTTON_KEY_F3 = 292, // GLFW_KEY_F3
	BUTTON_KEY_F4 = 293, // GLFW_KEY_F4
	BUTTON_KEY_F5 = 294, // GLFW_KEY_F5
	BUTTON_KEY_F6 = 295, // GLFW_KEY_F6
	BUTTON_KEY_F7 = 296, // GLFW_KEY_F7
	BUTTON_KEY_F8 = 297, // GLFW_KEY_F8
	BUTTON_KEY_F9 = 298, // GLFW_KEY_F9
	BUTTON_KEY_F10 = 299, // GLFW_KEY_F10
	BUTTON_KEY_F11 = 300, // GLFW_KEY_F11
	BUTTON_KEY_F12 = 301, // GLFW_KEY_F12

	BUTTON_KEY_MINUS = 45, // GLFW_KEY_MINUS
	BUTTON_KEY_EQUAL = 61, // GLFW_KEY_EQUAL
	BUTTON_KEY_GRAVE_ACCENT = 96, // GLFW_KEY_GRAVE_ACCENT
	BUTTON_KEY_DELETE = 261, // GLFW_KEY_DELETE

	BUTTON_KEY_LEFT_ALT = 342, // GLFW_KEY_LEFT_ALT,
	BUTTON_KEY_RIGHT_ALT = 346, // GLFW_KEY_RIGHT_ALT,
	BUTTON_KEY_LEFT_CTRL = 341, // GLFW_KEY_LEFT_CONTROL,
	BUTTON_KEY_RIGHT_CTRL = 345, // GLFW_KEY_RIGHT_CONTROL,
	BUTTON_KEY_LEFT_SHIFT = 340, // GLFW_KEY_LEFT_SHIFT,
	BUTTON_KEY_RIGHT_SHIFT = 344, // GLFW_KEY_RIGHT_SHIFT,
	BUTTON_KEY_TAB = 258, // GLFW_KEY_TAB,

	BUTTON_KEY_ENTER = 257, // GLFW_KEY_ENTER,
	BUTTON_KEY_BACKSPACE = 259, // GLFW_KEY_BACKSPACE,
	BUTTON_KEY_SPACE = 32, // GLFW_KEY_SPACE,
	BUTTON_KEY_ESCAPE = 256, // GLFW_KEY_ESCAPE,
	BUTTON_KEY_LEFT = 263, // GLFW_KEY_LEFT,
	BUTTON_KEY_RIGHT = 262, // GLFW_KEY_RIGHT,
	BUTTON_KEY_UP = 265, // GLFW_KEY_UP,
	BUTTON_KEY_DOWN = 264, // GLFW_KEY_DOWN,

	BUTTON_KEY_COMMA = 44, // GLFW_KEY_COMMA,
	BUTTON_KEY_PERIOD = 46, // GLFW_KEY_PERIOD,
	BUTTON_KEY_SLASH = 47, // GLFW_KEY_SLASH,
	BUTTON_KEY_BSLASH = 92, // GLFW_KEY_BACKSLASH,
	BUTTON_KEY_LEFT_BRACKET = 91, // GLFW_KEY_LEFT_BRACKET,
	BUTTON_KEY_RIGHT_BRACKET = 93, // GLFW_KEY_RIGHT_BRACKET,
	BUTTON_KEY_SEMICOLON = 59, // GLFW_KEY_SEMICOLON,
	BUTTON_KEY_APOSTROPHE = 39, // GLFW_KEY_APOSTROPHE,

	BUTTON_MOD_CONTROL = 0x0002, // GLFW_MOD_CONTROL,
	BUTTON_MOD_SHIFT = 0x0001, // GLFW_MOD_SHIFT,
	BUTTON_MOD_ALT = 0x0004, // GLFW_MOD_ALT,
	BUTTON_MOD_SUPER = 0x0008, // GLFW_MOD_SUPER
};
