#include "InputTypes.h"
#include "../Scripting/ScriptSystem.h"

// Use this macros to register the ButtonCode with the global object
#define REGISTER(x) global->Set(system->GetString(#x), v8::Int32::New(system->GetIsolate(), x))

void InstallButtonCodesIntoScripting(ScriptSystem* system)
{
	// Get the global namespace obj
	auto global = system->GetContext()->GetLocal()->Global();

	REGISTER(BUTTON_MOUSE_LEFT);
	REGISTER(BUTTON_MOUSE_MIDDLE);
	REGISTER(BUTTON_MOUSE_RIGHT);

	REGISTER(BUTTON_KEY_0);
	REGISTER(BUTTON_KEY_1);
	REGISTER(BUTTON_KEY_2);
	REGISTER(BUTTON_KEY_3);
	REGISTER(BUTTON_KEY_4);
	REGISTER(BUTTON_KEY_5);
	REGISTER(BUTTON_KEY_6);
	REGISTER(BUTTON_KEY_7);
	REGISTER(BUTTON_KEY_8);
	REGISTER(BUTTON_KEY_9);

	REGISTER(BUTTON_KEY_A);
	REGISTER(BUTTON_KEY_B);
	REGISTER(BUTTON_KEY_C);
	REGISTER(BUTTON_KEY_D);
	REGISTER(BUTTON_KEY_E);
	REGISTER(BUTTON_KEY_F);
	REGISTER(BUTTON_KEY_G);
	REGISTER(BUTTON_KEY_H);
	REGISTER(BUTTON_KEY_I);
	REGISTER(BUTTON_KEY_J);
	REGISTER(BUTTON_KEY_K);
	REGISTER(BUTTON_KEY_L);
	REGISTER(BUTTON_KEY_M);
	REGISTER(BUTTON_KEY_N);
	REGISTER(BUTTON_KEY_O);
	REGISTER(BUTTON_KEY_P);
	REGISTER(BUTTON_KEY_Q);
	REGISTER(BUTTON_KEY_R);
	REGISTER(BUTTON_KEY_S);
	REGISTER(BUTTON_KEY_T);
	REGISTER(BUTTON_KEY_U);
	REGISTER(BUTTON_KEY_V);
	REGISTER(BUTTON_KEY_W);
	REGISTER(BUTTON_KEY_X);
	REGISTER(BUTTON_KEY_Y);
	REGISTER(BUTTON_KEY_Z);

	REGISTER(BUTTON_KEY_F1);
	REGISTER(BUTTON_KEY_F2);
	REGISTER(BUTTON_KEY_F3);
	REGISTER(BUTTON_KEY_F4);
	REGISTER(BUTTON_KEY_F5);
	REGISTER(BUTTON_KEY_F6);
	REGISTER(BUTTON_KEY_F7);
	REGISTER(BUTTON_KEY_F8);
	REGISTER(BUTTON_KEY_F9);
	REGISTER(BUTTON_KEY_F10);
	REGISTER(BUTTON_KEY_F11);
	REGISTER(BUTTON_KEY_F12);
	
	REGISTER(BUTTON_KEY_MINUS);
	REGISTER(BUTTON_KEY_EQUAL);
	REGISTER(BUTTON_KEY_GRAVE_ACCENT);
	REGISTER(BUTTON_KEY_DELETE);

	REGISTER(BUTTON_KEY_LEFT_ALT);
	REGISTER(BUTTON_KEY_RIGHT_ALT);
	REGISTER(BUTTON_KEY_LEFT_CTRL);
	REGISTER(BUTTON_KEY_RIGHT_CTRL);
	REGISTER(BUTTON_KEY_LEFT_SHIFT);
	REGISTER(BUTTON_KEY_RIGHT_SHIFT);
	REGISTER(BUTTON_KEY_TAB);

	REGISTER(BUTTON_KEY_ENTER);
	REGISTER(BUTTON_KEY_BACKSPACE);
	REGISTER(BUTTON_KEY_SPACE);
	REGISTER(BUTTON_KEY_ESCAPE);
	REGISTER(BUTTON_KEY_LEFT);
	REGISTER(BUTTON_KEY_RIGHT);
	REGISTER(BUTTON_KEY_UP);
	REGISTER(BUTTON_KEY_DOWN);

	REGISTER(BUTTON_KEY_COMMA);
	REGISTER(BUTTON_KEY_PERIOD);
	REGISTER(BUTTON_KEY_SLASH);
	REGISTER(BUTTON_KEY_BSLASH);
	REGISTER(BUTTON_KEY_LEFT_BRACKET);
	REGISTER(BUTTON_KEY_RIGHT_BRACKET);
	REGISTER(BUTTON_KEY_SEMICOLON);
	REGISTER(BUTTON_KEY_APOSTROPHE);
}