#pragma once

enum ObjectType
{
	// WARNING: THE ORDER OF THESE MUST NOT BE CHANGED! FOR MAP LOADING!
	SHADER, MATERIAL, ENTITY, MAP, CAMERA, TRANSFORM, MESH, MESH_RENDERER, SCRIPT, SCRIPT_COMPONENT, TEST_RENDERER,
	TEXTURE_ASSET, SHADER_ASSET, MATERIAL_ASSET, MODEL_ASSET, MAP_ASSET, SCRIPT_ASSET, AUDIO_ASSET, AUDIO_SOURCE
};
